### ISSUE TITLE
can't write a simple demo in vs

### ISSUE THREAD

**Issue by zjydhr** [juj/vs-tool#11]
![untitled](https://f.cloud.github.com/assets/5027412/847087/df7a8e3a-f431-11e2-8f3f-795f5ca016b1.png)
![untitled2](https://f.cloud.github.com/assets/5027412/847092/fbe7ab02-f431-11e2-8bbb-cb065c5a6221.png)

I can run the hello_world.cpp in tests\msvc10
but when I write a new one and config follow the tutorial, It can not run.
Pictures shows the diff, but even I changed "$(VCTargetsPath)\Platforms\Emscripten\run_in_node.bat" to "xxx\iexplore.exe", it did not work too....

**Comment by juj** [comment]
You are not supposed to change run_in_node.bat to point to a browser. Node is used when the Configuration Type of the project is "Application (.js)". Js builds cannot be run in a brower.

Try changing the Configuration Type first to "HTML with Embedded JS (.html)", and after that setting The Debugging->Command property to e.g. "C:\Program Files (x86)\Mozilla Firefox\firefox.exe". Does that help?

**Comment by juj** [comment]
There was an update that configuration type is no longer used, but the file suffix alone controls the configuration type, so setting the file type to .js opens in node, and setting file type to .html opens in browser. Let me know if latest master still gives issues.
