### ISSUE TITLE
Can't compile simple test

### ISSUE THREAD

**Issue by TrevorSundberg** [juj/vs-tool#13]
When compiling:

```
#include <stdio.h>

int main(void)
{
  printf("hello\n");
  return 0;
}
```

I get the error:

```
1>InitializeBuildStatus:
1>  Touching "Emscripten\Debug\TestEmscripten.unsuccessfulbuild".
1>ClCompile:
1>  main.cpp
1>GCCLINK : error root: 
1>  subprocess.Popen(args=C:/mingw64/bin\llvm-nm C:/tmp\tmp_htxfg\main_0.o) failed! Exception [Error 6] The handle is invalid
1>  
1>  Traceback (most recent call last):
1>    File "C:\Users\Trevor\Documents\GitHub\emscripten\\emcc", line 1390, in <module>
1>      symbolses = map(lambda temp_file: shared.Building.llvm_nm(temp_file), temp_files)
1>    File "C:\Users\Trevor\Documents\GitHub\emscripten\\emcc", line 1390, in <lambda>
1>      symbolses = map(lambda temp_file: shared.Building.llvm_nm(temp_file), temp_files)
1>    File "C:\Users\Trevor\Documents\GitHub\emscripten\tools\shared.py", line 1043, in llvm_nm
1>      output = Popen([LLVM_NM, filename], stdout=stdout, stderr=stderr).communicate()[0]
1>    File "C:\Users\Trevor\Documents\GitHub\emscripten\tools\shared.py", line 52, in __init__
1>      raise e
1>  WindowsError: [Error 6] The handle is invalid
```

I made sure the C:\tmp directory existed (maybe the / is an issue?). Moreover, I can't seem to compile with Clang because I get this error:

```
1>clang : warning : argument '-fcatch-undefined-behavior' is deprecated, use '-fsanitize=undefined' instead
1>main.o : error LNK2019: unresolved external symbol __main referenced in function main
1>main.o : error LNK2019: unresolved external symbol printf referenced in function main
1>LINK : error LNK2001: unresolved external symbol mainCRTStartup
1>C:/Users/Trevor/documents/visual studio 2010/Projects/TestEmscripten/Clang/Debug/TestEmscripten.exe : fatal error LNK1120: 3 unresolved externals
```

I can compile/run the file using clang from the command line just fine:
`clang tests/main.cpp -o main.exe`
I can also compile with Emscripten:
`python2 emcc tests/main.cpp -o main.html`
Any ideas?

**Comment by juj** [comment]
Similar kind of issues have been reported at emscripten bug tracker and irc. An issue is that one should use / as path delimiter on Windows to avoid the \t popping up. Another issue is that the emscripten guide has been updated (for some unknown reason to me) to recommend installing mingw64, but I don't think it should be used at all, and instead it's best to make sure that all related executables are 32-bit, or Visual Studio seems to have problems invoking them.

**Comment by TrevorSundberg** [comment]
Ok thanks. When you say \t, do you mean any escape characters? I hadn't thought of that, but I could always double escape \ for python. I'll also attempt to install mingw32 also to see how it goes.

**Comment by juj** [comment]
By \t I mean an unfortunate mixup that occurs somewhere along the way that makes some part of the toolchain treat \t in e.g. "C:\tmp" as "C: 'tab character' mp". Double-escaping should work, or using forward slashes.

**Comment by juj** [comment]
Let me close this issue - feel free to reopen if there is still any trouble.
