### ISSUE TITLE
Visual Studio 2012 support

### ISSUE THREAD

**Issue by shaochun** [juj/vs-tool#14]
Hi juj, 

do you have any plans making vs-tool compatible with Visual Studio 2012?

thanks.

**Comment by juj** [comment]
Hi shaochun,

I don't currently use VS2012, so I am not pursuing adding support for it at the moment. If/when I get my hands on a new Win8 box with a VS2012 dev environment in the future, I can try seeing about the errors, but I can't promise anything at present.

**Comment by shaochun** [comment]
no prob, thanks for the follow-up.

**Comment by MatthewSmit** [comment]
I tried installing it how you would with VS2010 and replacing /10.0/ with /11.0/ in one of the files.
While the mingw option shows up and I can select it and change all the options, as soon as I apply the configuration VS crashes.

**Comment by shaochun** [comment]
this must be caused by the MSBuild process when using vs2012, but mingw might be a total different story.

**Comment by juj** [comment]
There are two issues tracking VS2012 support. Let me close this one in favor of issue #5, since it carries more information.
