### ISSUE TITLE
README installation instructions differ from Emscripten instructions

### ISSUE THREAD

**Issue by MarkCallow** [juj/vs-tool#17]
The installation instructions in vs-tool/README differ from those given in https://github.com/kripken/emscripten/wiki/Using-Emscripten-on-Windows.

Its confusing.

**Comment by juj** [comment]
Is there some part that is outdated or contradicting? What do you think is the source of confusion?

Looking at the change history for the emscripten wiki page, I see it recommends installing 64-bit versions of all software (python, node, gcc, clang), and that change was made to the instructions by vyuk, but I am not sure why he changed it as he did. I did not follow that guide, but my system has 32-bit versions of all those tools. Here is the version of instructions I wrote up at the time I set up my system: https://github.com/kripken/emscripten/wiki/Using-Emscripten-on-Windows/4bc45bfa692fd57491af72d1897856c8238fe9ff

Note that for some time, there was the pythonemcc helper executable (found in the vs-tool repo) that was used to workaround the lack of .rsp file support and python invokation, but those were implemented to emscripten itself, so those should not be needed anymore (but should not hurt if used either)

**Comment by MarkCallow** [comment]
I am referring to the instructions for installing vs-tool. The Using Emscripten page says to copy the Emscripten and CLang directories from vs-tool to the Platforms directory of MSBuild. The README file says to copy the vs-tool directory to the Platforms directory.

**Comment by MarkCallow** [comment]
Where did you get the 32-bit version of Clang from? The build whose link is given on the Using-Emscripten-on-Windows has only a 64-bit version.

**Comment by juj** [comment]
I build Clang manually from sources. See the instructions here if you want to try that: https://github.com/kripken/emscripten/wiki/Using-Emscripten-from-Visual-Studio-2010/045a71d891635f5c500ae3a67a3b8a6e5da9b63d

**Comment by juj** [comment]
Let me close this issue, the 32-bit vs 64-bit bitness issue has gotten some attention, and the README has been updated since.
