### ISSUE TITLE
Error message --minify 1 deprecated with current emscripten version

### ISSUE THREAD

**Issue by marc40000** [juj/vs-tool#18]
Hi !

I jsut updated my emscripten clone and got a message that --minify 1 is deprecated and --minify 0 is the only supported Setting. I don't know if --minify 0 is the same as not adding it at all, but at least switching it of in the EMCC Linker Options of the project settings made it compile again. Maybe the Default Setting for Release should be set accordingly - or the Option should be removed alltogether?

Best regards
    intripoon

**Comment by marc40000** [comment]
I just checked with azakai on IRC. He said, minify is on by Default and adding --minify 0 disables it. --minify 1 is deprecated and doesn't work anymore.

**Comment by juj** [comment]
Thanks for reporting. The build options page will need some updates, it has not been checked in a while.
