### ISSUE TITLE
unnecessary warnings when building msvc10 projects

### ISSUE THREAD

**Issue by MarkCallow** [juj/vs-tool#19]
I get the following 2 warnings when building the tests/msvc10 projects.

In my environment we consider warnings to be errors and anyway having too many warnings is bad as they can obscure real problems. Indeed, in this case, some of the projects have additional warnings which are really hard to spot among the noise from these 2. So we would like to see these issues fixed.

clang : warning : argument unused during compilation: '-nostdinc++'

GCCCOMPILE : warning root: -I or -L of an absolute path "-IC:/<emscripten root>/tests/msvc10/../glbook/Common"

The first occurs with all projects even when compiling a .cpp file. It is not set in the arguments passed to emcc so emcc itself must be setting it when calling clang and will therefore be a problem regardless of use of VS10.

The second occurs in a large number of projects. It is because the projects use "$(SolutionDir)../glbook/Common" in the Extra Include Directories field. It can be fixed by simply removing $(SolutionDir) as the current directory, when the compile is run, will be the project directory which is the same as $(SolutionDir).

**Comment by MarkCallow** [comment]
Oops. I intended to file this in emscripten issues. Actually I'm not sure which project is responsible for the msvc10 project files. It looks like they were generated by CMake but the tests/cmake/*/CMakeLists.txt files only lists hello_world.

**Comment by juj** [comment]
The msvc10 project solution is maintained by hand, and not via CMake.

The warning "clang : warning : argument unused during compilation: '-nostdinc++'" should be gone nowadays, it was spawned internally by emcc for some time, but now it should be muted. The second warning comes from this porting aid mechanism in emcc that is by default on - it gives a warning about whenever one passes -Iabsolutepath, the motivation being that those would be pointing to native system directories. To mute that warning, one can pass -Wno-warn-absolute-paths.

I tried rebuilding msvc10 project today, and it seems that neither of these warnings are printed anymore, so let me close this issue for now.
