### ISSUE TITLE
setting LEGACY_GL_EMULATION = 1

### ISSUE THREAD

**Issue by Culzean** [juj/vs-tool#28]
Uncaught Legacy GL function (glGenVertexArrays) called. You need to compile with -s LEGACY_GL_EMULATION=1 to enable legacy GL emulation.

How can I set this to 1 from vs2010 with the emscripten tool?

**Comment by juj** [comment]
Try dropping it in the Project Properties -> Linker -> Command Line -> Additional Options box. Does that work?

**Comment by Culzean** [comment]
I haven't been able to get this work. Here's the output, I could be using the additional options wrong,

1>GCCLINK : warning root: treating -s as linker option and not as -s OPT=VALUE for js compilation
1>GCCLINK : error root: LEGACY_GL_EMULATION: No such file or directory ("LEGACY_GL_EMULATION" was expected to be an input file, based on the commandline arguments provided)

It's a strange error message; glGenVertexArrays is not legacy. Though neither is it WebGL.

**Comment by juj** [comment]
For an example, see the sdl_ogl project in emscripten/tests/msvc10/tests_msvc10.sln. That adds -s LEGACY_GL_EMULATION=1 option in the build.

**Comment by Culzean** [comment]
Thanks juj, got that sorted out and no error now.

**Comment by juj** [comment]
Great! Closing this.
