### ISSUE TITLE
Wrong readme?

### ISSUE THREAD

**Issue by Gargo** [juj/vs-tool#30]
"Copy the folder platform\ from this repository to C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\platform\ (or the corresponding location where MSBuild exists on your system)"

ok, where is this folder in this repository?

**Comment by juj** [comment]
The word `platform` is in italics in the readme, trying to convey the meaning "For each `x`, you are interested in using, copy the folder `x/` to .." . If that is confusing, I can try to rephrase or clarify it. Does that help?

**Comment by juj** [comment]
Let me close this. Feel free to comment if you figure out a better wording. Thanks!
