### ISSUE TITLE
Emscripten location taken from environment var

### ISSUE THREAD

**Issue by juancampa** [juj/vs-tool#31]
Every time I need to change the Emscripten version being used I have to restart Visual Studio after changing the EMSCRIPTEN environment variable. Since there's already a way to define which version I want to use (through emsdk) Is it possible to make vs-tool take the emscripten path from what's configured with emsdk (i.e. the .emscripten file)?

The idea is to make switching of emscripten versions simply a matter of writing "emsdk activate <version>" in a command prompt.

Thanks, awesome work btw.

**Comment by juj** [comment]
Thanks! I've done some work on making env. vars automatically update to the system on emsdk activate, but it's somewhat tricky due to UAC elevation requirements and other things, but I'm looking to have this fixed by the next emsdk release.

**Comment by juancampa** [comment]
That would be really cool. Thanks mate!

**Comment by juj** [comment]
The 1.16.0 emsdk now does the EMSCRIPTEN environment variable set step when you call 'emsdk activate', so the result should be visible in Visual Studio as well (need to restart Visual Studio for it to see the changes). I'll close this now, let me know if there still are issues.
