### ISSUE TITLE
Visual Studio 2010 Wrong setup - "no result showing up"

### ISSUE THREAD

**Issue by ArwedSchmidt** [juj/vs-tool#32]
Hello,
I've been setting up this tool and stumbled upon some issues with the configuration of emscriptens "/tests/msvc10/" Solution project. I would compile and compile, but it would not generate any .js file. Here's what was going on:

In every project's setting there is a default build extension. This was not set, causing my setup to let emcc generate an .exe file.. I needed to set this to .js or .html to get some output in C:\Users\xxxxxx\Documents\GitHub\emscripten\tests\msvc10\Emscripten\Release\glbook_2_Hello_Triangle.html
I could then setup the debugger to be a browser debugger or local debugger ("chrome.exe C:\path\to\file.html").
Another issue is with some parameters. It says "minify 1" is deprecated, so the option should be removed (it will do automatically). Also, you cant set the typedArrays config with a = sign, emcc complains about it and if you dont "echo commands" it will do so totally silent - you won't notice whats going wrong. 

These are the configs I needed to change in order to setup your tool. Thank you for your great work - let's hope emscripten, asm.js and WebGL will get a bit more mature soon so we can start to pwn :-)

**Comment by rroa** [comment]
@ArwedSchmidt could you be more specific about the changes you had to make in order to make this work? I'm having the same issue. 

I changed the target extension manually to something like ".html", but that didn't do the trick.

**Comment by rroa** [comment]
Ok. So I kept fiddling with the project settings until I got it working. I still haven't been able to open a browser and display the generated HTML using CTRL + F5, not sure if I have my ENV variables set properly for that.

To anyone having the same problem just change the _Property Pages_ -> _Configuration Properties_ -> _General_ -> _Configuration Type_ to Application (.js or .html) and manually set the _Property Pages_ -> _Configuration Properties_ -> _General_ -> _Target Extension_ up top. That should do it.

**Comment by ArwedSchmidt** [comment]
Sure. Once you have a file output in e.g. C:\Users\arwed\Documents\GitHub\emscripten\tests\msvc10\Emscripten\Release\glbook_2_Hello_Triangle.html, its as simple as setting "Config" => "Debugger" to "Local Windows Debugger", giving it these two lines as argument 1 ("Command") and 2 ("Arguments"):

C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
C:\Users\arwed\Documents\GitHub\emscripten\tests\msvc10\Emscripten\Release\glbook_2_Hello_Triangle.html

Let me know if that doesn't do the job for you.

**Comment by rroa** [comment]
It worked just fine. Thanks.

Instead of using the path to the actual browser executable I used the 'EMCC_WEBBROWSER_EXE' environment variable.

**Comment by juj** [comment]
This should be fixed in vs-tool 0.9.4 as part of http://tiny.cc/2npmix , so let me close this. Please do reopen or add a new issue if there's still something off there.
