### ISSUE TITLE
Windows8/mingw-w64 : doesn't work

### ISSUE THREAD

**Issue by ghost** [juj/vs-tool#36]
Hi,

I am testing vs-tool plugin on Windows 8 64 bits/VS2010 SP1/mingw-w64 and I have some errors.
I am trying to recompile wxwidgets-3.0.0 using wx_vc7.sln but I get the following errors :

Error   1   error MSB6006: "cmd.exe" exited with code 9009. C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets   151 6   richtext
Error   2   error MSB6006: "cmd.exe" exited with code 9009. C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets   151 6   propgrid
Error   3   error : unknown type name 'class'   C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\include\ILexer.h 23  2   wxscintilla
Error   4   error : expected '=', ',', ';', 'asm' or '**attribute**' before '{' token   C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\include\ILexer.h 23  18  wxscintilla
Error   5   error : unknown type name 'class'   C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\include\ILexer.h 50  2   wxscintilla
Error   6   error : expected '=', ',', ';', 'asm' or '**attribute**' before '{' token   C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\include\ILexer.h 50  15  wxscintilla
Error   7   error : unknown type name 'class'   C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\include\ILexer.h 65  2   wxscintilla
Error   8   error : expected '=', ',', ';', 'asm' or '**attribute**' before '{' token   C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\include\ILexer.h 65  16  wxscintilla
Error   9   error MSB6006: "cmd.exe" exited with code 9009. C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets   151 6   aui
Error   10  error : unknown type name 'class'   C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\PropSetSimple.h   15  2   wxscintilla
Error   11  error : expected '=', ',', ';', 'asm' or '**attribute**' before '{' token   C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\PropSetSimple.h   15  22  wxscintilla
Error   12  error : unknown type name 'class'   C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\WordList.h    17  2   wxscintilla
Error   13  error : expected '=', ',', ';', 'asm' or '**attribute**' before '{' token   C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\WordList.h    17  17  wxscintilla
Error   14  error : unknown type name 'class'   C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\LexAccessor.h 15  2   wxscintilla
Error   15  error : expected '=', ',', ';', 'asm' or '**attribute**' before '{' token   C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\LexAccessor.h 15  20  wxscintilla
Error   16  error : unknown type name 'class'   C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\Accessor.h    17  2   wxscintilla
Error   17  error : unknown type name 'class'   C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\Accessor.h    18  2   wxscintilla
Error   18  error MSB6006: "cmd.exe" exited with code 9009. C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets   151 6   xrc
Error   19  error : unknown type name 'class'   C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\Accessor.h    19  2   wxscintilla
Error   20  error MSB6006: "cmd.exe" exited with code 9009. C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets   151 6   ribbon
Error   21  error : expected declaration specifiers or '...' before '*' token   C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\Accessor.h    21  16  wxscintilla
Error   22  error : unknown type name 'class'   C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\Accessor.h    23  2   wxscintilla
Error   23  error MSB6006: "cmd.exe" exited with code 9009. C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets   151 6   xml
Error   24  error : expected '=', ',', ';', 'asm' or '**attribute**' before ':' token   C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\Accessor.h    23  17  wxscintilla
Error   25  error : expected '=', ',', ';', 'asm' or '**attribute**' before ':' token   C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\Accessor.cxx  28  10  wxscintilla
Error   26  error MSB6006: "cmd.exe" exited with code 9009. C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets   151 6   qa
Error   27  error : expected '=', ',', ';', 'asm' or '**attribute**' before ':' token   C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\Accessor.cxx  31  14  wxscintilla
Error   28  error MSB6006: "cmd.exe" exited with code 9009. C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets   151 6   webview
Error   29  error MSB6006: "cmd.exe" exited with code 9009. C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets   151 6   adv
Error   30  error MSB6006: "cmd.exe" exited with code 9009. C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets   151 6   html
Error   31  error : expected '=', ',', ';', 'asm' or '**attribute**' before ':' token   C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\Accessor.cxx  35  14  wxscintilla
Error   32  error MSB6006: "cmd.exe" exited with code 9009. C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets   151 6   core
Error   33  error MSB6006: "cmd.exe" exited with code 9009. C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets   151 6   net
Error   34  error : can't create vc_mswud/media/: Permission denied C:\Developer\wxWidgets-3.0.0\build\msw\GCCCOMPILE   media
Error   35  error MSB6006: "cmd.exe" exited with code 9009. C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets   151 6   base
Error   36  error MSB6006: "cmd.exe" exited with code 9009. C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets   151 6   gl
Error   37  error : can't create vc_mswud/wxtiff/: Permission denied    C:\Developer\wxWidgets-3.0.0\build\msw\GCCCOMPILE   wxtiff
Error   38  error MSB6006: "cmd.exe" exited with code 9009. C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets   151 6   stc
Error   39  error : can't create vc_mswud/wxjpeg/: Permission denied    C:\Developer\wxWidgets-3.0.0\build\msw\GCCCOMPILE   wxjpeg
Error   40  error : can't create vc_mswud/wxzlib/: Permission denied    C:\Developer\wxWidgets-3.0.0\build\msw\GCCCOMPILE   wxzlib
Error   41  error : can't create vc_mswud/wxexpat/: Permission denied   C:\Developer\wxWidgets-3.0.0\build\msw\GCCCOMPILE   wxexpat
Error   42  error : can't create vc_mswud/wxpng/: Permission denied C:\Developer\wxWidgets-3.0.0\build\msw\GCCCOMPILE   wxpng
Error   43  error : can't create vc_mswud/wxregex/: Permission denied   C:\Developer\wxWidgets-3.0.0\build\msw\GCCCOMPILE   wxregex
    132 IntelliSense: PCH warning: header stop cannot be in a macro or #if block.  An intellisense PCH file was not generated.  c:\developer\wxwidgets-3.0.0\src\stc\scintilla\include\ilexer.h 12  1   

and from output :

1>------ Build started: Project: wxscintilla, Configuration: Debug MinGW ------
2>------ Build started: Project: richtext, Configuration: Debug MinGW ------
3>------ Build started: Project: propgrid, Configuration: Debug MinGW ------
4>------ Build started: Project: ribbon, Configuration: Debug MinGW ------
2>  Creating ....\lib\vc_lib\mswud\wx\setup.h
2>          1 fichier(s) copié(s).
2>  Creating ....\lib\vc_lib\mswud\wx\msw\rcdefs.h
2> 'cl' is not recognized as an internal or external command operable program or batch file.
2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB6006: "cmd.exe" exited with code 9009.
3>  Creating ....\lib\vc_lib\mswud\wx\setup.h
3>          1 fichier(s) copié(s).
3>  Creating ....\lib\vc_lib\mswud\wx\msw\rcdefs.h
3>  'cl' is not recognized as an internal or external command operable program or batch file.
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB6006: "cmd.exe" exited with code 9009.
5>------ Build started: Project: aui, Configuration: Debug MinGW ------
1>  Accessor.cxx
1>  C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\Accessor.cxx(15): includes this header: 0:
1>C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\include\ILexer.h(23,1): error : unknown type name 'class'
1>   class IDocument {
1>   ^
1>C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\include\ILexer.h(23,17): error : expected '=', ',', ';', 'asm' or '**attribute**' before '{' token
1>   class IDocument {
1>                   ^
1>C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\include\ILexer.h(50,1): error : unknown type name 'class'
1>   class ILexer {
1>   ^
1>C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\include\ILexer.h(50,14): error : expected '=', ',', ';', 'asm' or '**attribute**' before '{' token
1>   class ILexer {
1>                ^
1>C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\include\ILexer.h(65,1): error : unknown type name 'class'
1>   class ILoader {
1>   ^
1>C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\include\ILexer.h(65,15): error : expected '=', ',', ';', 'asm' or '**attribute**' before '{' token
1>   class ILoader {
5>  Creating ....\lib\vc_lib\mswud\wx\setup.h
5>          1 fichier(s) copié(s).
5>  Creating ....\lib\vc_lib\mswud\wx\msw\rcdefs.h
5> 'cl' is not recognized as an internal or external command operable program or batch file.
5>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB6006: "cmd.exe" exited with code 9009.
6>------ Build started: Project: xrc, Configuration: Debug MinGW ------
1>                 ^
1>  C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\Accessor.cxx(19): includes this header: 0:
1>C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\PropSetSimple.h(15,1): error : unknown type name 'class'
1>   class PropSetSimple {
1>   ^
1>C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\PropSetSimple.h(15,21): error : expected '=', ',', ';', 'asm' or '**attribute**' before '{' token
1>   class PropSetSimple {
1>                       ^
1>  C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\Accessor.cxx(20): includes this header: 0:
1>C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\WordList.h(17,1): error : unknown type name 'class'
1>   class WordList {
1>   ^
1>C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\WordList.h(17,16): error : expected '=', ',', ';', 'asm' or '**attribute**' before '{' token
1>   class WordList {
1>                  ^
1>  C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\Accessor.cxx(21): includes this header: 0:
1>C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\LexAccessor.h(15,1): error : unknown type name 'class'
1>   class LexAccessor {
1>   ^
1>C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\LexAccessor.h(15,19): error : expected '=', ',', ';', 'asm' or '**attribute**' before '{' token
1>   class LexAccessor {
1>                     ^
1>  C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\Accessor.cxx(22): includes this header: 0:
1>C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\Accessor.h(17,1): error : unknown type name 'class'
1>   class Accessor;
6>  Creating ....\lib\vc_lib\mswud\wx\setup.h
6>          1 fichier(s) copié(s).
6>  Creating ....\lib\vc_lib\mswud\wx\msw\rcdefs.h
1>   ^
1>C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\Accessor.h(18,1): error : unknown type name 'class'
1>   class WordList;
6>  'cl' is not recognized as an internal or external command operable program or batch file.
6>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB6006: "cmd.exe" exited with code 9009.
7>------ Build started: Project: xml, Configuration: Debug MinGW ------
1>   ^
1>C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\Accessor.h(19,1): error : unknown type name 'class'
1>   class PropSetSimple;
4>  Creating ....\lib\vc_lib\mswud\wx\setup.h
4>          1 fichier(s) copié(s).
4>  Creating ....\lib\vc_lib\mswud\wx\msw\rcdefs.h
4>  'cl' n'est pas reconnu en tant que commande interne
4>  ou externe, un programme exécutable ou un fichier de commandes.
4>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB6006: "cmd.exe" exited with code 9009.
8>------ Build started: Project: qa, Configuration: Debug MinGW ------
1>   ^
1>C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\Accessor.h(21,15): error : expected declaration specifiers or '...' before '_' token
1>   typedef bool (_PFNIsCommentLeader)(Accessor &styler, int pos, int len);
1>                 ^
1>C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\Accessor.h(23,1): error : unknown type name 'class'
1>   class Accessor : public LexAccessor {
7>  Creating ....\lib\vc_lib\mswud\wx\setup.h
7>          1 fichier(s) copié(s).
7>  Creating ....\lib\vc_lib\mswud\wx\msw\rcdefs.h
7>  'cl' n'est pas reconnu en tant que commande interne
7>  ou externe, un programme exécutable ou un fichier de commandes.
7>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB6006: "cmd.exe" exited with code 9009.
9>------ Build started: Project: webview, Configuration: Debug MinGW ------
1>   ^
1>C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\Accessor.h(23,16): error : expected '=', ',', ';', 'asm' or '**attribute**' before ':' token
1>   class Accessor : public LexAccessor {
1>                  ^
1>C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\Accessor.cxx(28,9): error : expected '=', ',', ';', 'asm' or '**attribute**' before ':' token
8>  Creating ....\lib\vc_lib\mswud\wx\setup.h
8>          1 fichier(s) copié(s).
8>  Creating ....\lib\vc_lib\mswud\wx\msw\rcdefs.h
8>  'cl' n'est pas reconnu en tant que commande interne
8>  ou externe, un programme exécutable ou un fichier de commandes.
8>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB6006: "cmd.exe" exited with code 9009.
1>   Accessor::Accessor(IDocument *pAccess_, PropSetSimple *pprops_) : LexAccessor(pAccess_), pprops(pprops_) {
9>  Creating ....\lib\vc_lib\mswud\wx\setup.h
9>          1 fichier(s) copié(s).
9>  Creating ....\lib\vc_lib\mswud\wx\msw\rcdefs.h
1>           ^
1>C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\Accessor.cxx(31,13): error : expected '=', ',', ';', 'asm' or '**attribute**' before ':' token
9>  'cl' n'est pas reconnu en tant que commande interne
9>  ou externe, un programme exécutable ou un fichier de commandes.
9>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB6006: "cmd.exe" exited with code 9009.
10>------ Build started: Project: html, Configuration: Debug MinGW ------
11>------ Build started: Project: media, Configuration: Debug MinGW ------
12>------ Build started: Project: adv, Configuration: Debug MinGW ------
12>  Creating ....\lib\vc_lib\mswud\wx\setup.h
12>          1 fichier(s) copié(s).
12>  Creating ....\lib\vc_lib\mswud\wx\msw\rcdefs.h
12>  'cl' n'est pas reconnu en tant que commande interne
12>  ou externe, un programme exécutable ou un fichier de commandes.
12>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB6006: "cmd.exe" exited with code 9009.
1>   int Accessor::GetPropertyInt(const char *key, int defaultValue) {
10>  Creating ....\lib\vc_lib\mswud\wx\setup.h
10>          1 fichier(s) copié(s).
10>  Creating ....\lib\vc_lib\mswud\wx\msw\rcdefs.h
10>  'cl' n'est pas reconnu en tant que commande interne
10>  ou externe, un programme exécutable ou un fichier de commandes.
10>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB6006: "cmd.exe" exited with code 9009.
13>------ Build started: Project: core, Configuration: Debug MinGW ------
1>               ^
1>C:\Developer\wxWidgets-3.0.0\src\stc\scintilla\lexlib\Accessor.cxx(35,13): error : expected '=', ',', ';', 'asm' or '**attribute**' before ':' token
13>  Creating ....\lib\vc_lib\mswud\wx\setup.h
11>  dummy.cpp
13>          1 fichier(s) copié(s).
13>  Creating ....\lib\vc_lib\mswud\wx\msw\rcdefs.h
13>  'cl' n'est pas reconnu en tant que commande interne
13>  ou externe, un programme exécutable ou un fichier de commandes.
13>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB6006: "cmd.exe" exited with code 9009.
14>------ Build started: Project: net, Configuration: Debug MinGW ------
14>  Creating ....\lib\vc_lib\mswud\wx\setup.h
14>          1 fichier(s) copié(s).
14>  Creating ....\lib\vc_lib\mswud\wx\msw\rcdefs.h
14>  'cl' n'est pas reconnu en tant que commande interne
14>  ou externe, un programme exécutable ou un fichier de commandes.
14>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB6006: "cmd.exe" exited with code 9009.
11>  Assembler messages:
15>------ Build started: Project: base, Configuration: Debug MinGW ------
11>GCCCOMPILE : Fatal error : can't create vc_mswud/media/: Permission denied
16>------ Build started: Project: gl, Configuration: Debug MinGW ------
15>  Creating ....\lib\vc_lib\mswud\wx\setup.h
15>          1 fichier(s) copié(s).
15>  Creating ....\lib\vc_lib\mswud\wx\msw\rcdefs.h
1>   int Accessor::IndentAmount(int line, int *flags, PFNIsCommentLeader pfnIsCommentLeader) {
1>               ^
15>  'cl' n'est pas reconnu en tant que commande interne
15>  ou externe, un programme exécutable ou un fichier de commandes.
15>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB6006: "cmd.exe" exited with code 9009.
16>  Creating ....\lib\vc_lib\mswud\wx\setup.h
16>          1 fichier(s) copié(s).
16>  Creating ....\lib\vc_lib\mswud\wx\msw\rcdefs.h
16>  'cl' n'est pas reconnu en tant que commande interne
16>  ou externe, un programme exécutable ou un fichier de commandes.
16>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB6006: "cmd.exe" exited with code 9009.
17>------ Build started: Project: wxexpat, Configuration: Debug MinGW ------
18>------ Build started: Project: wxtiff, Configuration: Debug MinGW ------
18>  tif_aux.c
17>  xmlparse.c
18>  Assembler messages:
18>GCCCOMPILE : Fatal error : can't create vc_mswud/wxtiff/: Permission denied
19>------ Build started: Project: stc, Configuration: Debug MinGW ------
20>------ Build started: Project: wxjpeg, Configuration: Debug MinGW ------
21>------ Build started: Project: wxpng, Configuration: Debug MinGW ------
20>  jcapimin.c
19>  Creating ....\lib\vc_lib\mswud\wx\setup.h
19>          1 fichier(s) copié(s).
19>  Creating ....\lib\vc_lib\mswud\wx\msw\rcdefs.h
19>  'cl' n'est pas reconnu en tant que commande interne
19>  ou externe, un programme exécutable ou un fichier de commandes.
19>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB6006: "cmd.exe" exited with code 9009.
20>  Assembler messages:
21>  png.c
20>GCCCOMPILE : Fatal error : can't create vc_mswud/wxjpeg/: Permission denied
22>------ Build started: Project: wxzlib, Configuration: Debug MinGW ------
22>  adler32.c
22>  Assembler messages:
22>GCCCOMPILE : Fatal error : can't create vc_mswud/wxzlib/: Permission denied
23>------ Build started: Project: wxregex, Configuration: Debug MinGW ------
23>  regcomp.c
17>  Assembler messages:
17>GCCCOMPILE : Fatal error : can't create vc_mswud/wxexpat/: Permission denied
21>  Assembler messages:
21>GCCCOMPILE : Fatal error : can't create vc_mswud/wxpng/: Permission denied
23>  Assembler messages:
23>GCCCOMPILE : Fatal error : can't create vc_mswud/wxregex/: Permission denied
========== Build: 0 succeeded, 23 failed, 0 up-to-date, 0 skipped ==========

Inside the project I have added the MinGW platform and set MINGW_BIN as shown below 

> C:\Users\Vincent>echo %MINGW_BIN%
> C:\Developer\mingw\mingw-w64\i686-4.9.0-win32-dwarf-rt_v3-rev2\mingw32\bin

Through cygwin shell here is the content of my MSBuild folder : 

Vincent@Vincent-PC /cygdrive/c/Program Files (x86)/MSBuild/Microsoft.Cpp/v4.0/Platforms
$ tree -L 1 .
.
|-- Clang
|-- Emscripten
|-- Itanium
|-- MinGW
|-- NaCl
|-- README.md
|-- Win32
|-- pythonemcc
`-- x64

More information, when I try to compile a single file from VS2010 I get the following error :

1>------ Build started: Project: ribbon, Configuration: Debug MinGW ------
1>  art_aui.cpp
1>  Assembler messages:
1>GCCCOMPILE : Fatal error : can't create vc_mswud/ribbon/: Permission denied
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

However the folder is created and contains the following files :

Vincent@Vincent-PC /cygdrive/c/Developer/wxWidgets-3.0.0/build/msw/vc_mswud/ribbon
$ ls -la
total 42K
----------+ 1 Vincent None 32K  4 juin  22:14 art_aui.d
----------+ 1 Vincent None 848  4 juin  22:14 gcc.compile.command.1.tlog
----------+ 1 Vincent None 110  4 juin  22:14 gcc.compile.read.1.tlog
----------+ 1 Vincent None 224  4 juin  22:14 gcc.compile.write.1.tlog
----------+ 1 Vincent None   0  4 juin  22:14 ribbon.write.1.tlog
----------+ 1 Vincent None 571  4 juin  22:14 wx_vc7_ribbon.log 

Vincent@Vincent-PC /cygdrive/c/Developer/wxWidgets-3.0.0/build/msw/vc_mswud/ribbon
$ less wx_vc7_ribbon.log

Build started 04/06/2014 22:14:40.
     1>Project "C:\Developer\wxWidgets-3.0.0\build\msw\wx_vc7_ribbon.vcxproj" on node 2 (ClCompile target(s)).
     1>ClCompile:
         C:\Developer\mingw\mingw-w64\i686-4.9.0-win32-dwarf-rt_v3-rev2\mingw32\bin\gcc.exe
         art_aui.cpp
         Assembler messages:
     1>GCCCOMPILE : Fatal error : can't create vc_mswud/ribbon/: Permission denied
     1>Done Building Project "C:\Developer\wxWidgets-3.0.0\build\msw\wx_vc7_ribbon.vcxproj" (ClCompile target(s)) -- FAILED.

Build FAILED.

Time Elapsed 00:00:02.01

---

if I try from a dos cmd I have a different error that has nothing to do with file permissions :

C:\Developer\wxWidgets-3.0.0\src\ribbon>C:\Developer\mingw\mingw-w64\i686-4.9.0-
win32-dwarf-rt_v3-rev2\mingw32\bin\gcc.exe art_aui.cpp
art_aui.cpp:11:23: fatal error: wx/wxprec.h: No such file or directory
 #include "wx/wxprec.h"
                       ^
compilation terminated.

**Comment by juj** [comment]
Try to first get a mingw32 build working outside vs-tool, and then check again with it. Enabling the Echo Command Lines option both in project compiler and linker settings can give a clue on what kind of commands the plugin is trying to invoke.

It says "Assembler Messages" in the output, so I'm not sure if it's trying to run the MS or GNU assembler - both of those are features that haven't been tested with vs-tool. Do smaller "hello world"-type projects without assembler files build ok?

**Comment by ghost** [comment]
OK I have found the problem, inside the vcxproj some files use a CustomBuild and they call the command : cl /EP /nologo 

``` xml
<CustomBuild Include="..\..\include\wx\msw\genrcdefs.h">
      <Message Condition="'$(Configuration)|$(Platform)'=='DLL Debug|Win32'">Creating $(OutDir)mswud\wx\msw\rcdefs.h</Message>
      <Command Condition="'$(Configuration)|$(Platform)'=='DLL Debug|Win32'">cl /EP /nologo "%(FullPath)" &gt; "$(OutDir)mswud\wx\msw\rcdefs.h"</Command>
      <Outputs Condition="'$(Configuration)|$(Platform)'=='DLL Debug|Win32'">$(OutDir)mswud\wx\msw\rcdefs.h;%(Outputs)</Outputs>
      <AdditionalInputs Condition="'$(Configuration)|$(Platform)'=='DLL Debug|Win32'">$(OutDir)mswud\wx\msw;%(AdditionalInputs)</AdditionalInputs>
      <Message Condition="'$(Configuration)|$(Platform)'=='DLL Release|Win32'">Creating $(OutDir)mswu\wx\msw\rcdefs.h</Message>
      <Command Condition="'$(Configuration)|$(Platform)'=='DLL Release|Win32'">cl /EP /nologo "%(FullPath)" &gt; "$(OutDir)mswu\wx\msw\rcdefs.h"</Command>
      <Outputs Condition="'$(Configuration)|$(Platform)'=='DLL Release|Win32'">$(OutDir)mswu\wx\msw\rcdefs.h;%(Outputs)</Outputs>
      <AdditionalInputs Condition="'$(Configuration)|$(Platform)'=='DLL Release|Win32'">$(OutDir)mswu\wx\msw;%(AdditionalInputs)</AdditionalInputs>
      <Message Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">Creating $(OutDir)mswud\wx\msw\rcdefs.h</Message>
      <Command Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">cl /EP /nologo "%(FullPath)" &gt; "$(OutDir)mswud\wx\msw\rcdefs.h"</Command>
      <Outputs Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">$(OutDir)mswud\wx\msw\rcdefs.h;%(Outputs)</Outputs>
      <AdditionalInputs Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">$(OutDir)mswud\wx\msw;%(AdditionalInputs)</AdditionalInputs>
      <Message Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">Creating $(OutDir)mswu\wx\msw\rcdefs.h</Message>
      <Message Condition="'$(Configuration)|$(Platform)'=='Release|x64'">Creating $(OutDir)mswu\wx\msw\rcdefs.h</Message>
      <Command Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">cl /EP /nologo "%(FullPath)" &gt; "$(OutDir)mswu\wx\msw\rcdefs.h"</Command>
      <Command Condition="'$(Configuration)|$(Platform)'=='Release|x64'">cl /EP /nologo "%(FullPath)" &gt; "$(OutDir)mswu\wx\msw\rcdefs.h"</Command>
      <Outputs Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">$(OutDir)mswu\wx\msw\rcdefs.h;%(Outputs)</Outputs>
      <Outputs Condition="'$(Configuration)|$(Platform)'=='Release|x64'">$(OutDir)mswu\wx\msw\rcdefs.h;%(Outputs)</Outputs>
      <AdditionalInputs Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">$(OutDir)mswu\wx\msw;%(AdditionalInputs)</AdditionalInputs>
    </CustomBuild>
```

**Comment by juj** [comment]
Thanks, let me close this as it was a project-specific issue.
