### ISSUE TITLE
Paths and file not found

### ISSUE THREAD

**Issue by marc40000** [juj/vs-tool#7]
Hi !

I just started using vs-tool so my following questions might not be issues with vs-tool but with me doing something wrong.

I installed mingw and vs-tool like documented except I didn't put vs-tool in the msbuild dir but instead the mingw dir in the msbuild dir. Otherwise, the compiler options didn't appear. This is quite strange because the readme states that a vs-tool dir should be there. It also states that the solution plattform I can create in the configuration manager is called "vs-tool" - but this way, I have "mingw" and "clang" etc.

Ok, when I create a solution plattform "mingw" and set the toolchain to mingw, I get the following error when I try to compile:

error MSB4062: The "GCCCompile" task could not be loaded from the assembly C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Emscripten\vs-android.Build.CPPTasks.Android.dll. Could not load file or assembly 'file:///C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Emscripten\vs-android.Build.CPPTasks.Android.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

The file exists at that path - even though I'm using mingw and not emscripten I copied all subdirs from the vs-tool to the msbuild dir.

What am I doing wrong here?

**Comment by juj** [comment]
Does it work after this change? https://github.com/juj/vs-tool/commit/2049b9cce40ef7e27dfe760419a3ef0ec7ba2723

**Comment by marc40000** [comment]
Fixed after feedback from clb in #emscripten on mozilla and a few changes. Thx. :)

**Comment by tparisi** [comment]
how did you fix it?

**Comment by juj** [comment]
The above commit should fix the issue, the .dll name was typoed, "-" vs "_".
